### ISSUE TITLE
Import from multiple source directories

### ISSUE THREAD

**Issue by ritzmann** [niol/lazygal#15]
How about allowing to import from multiple sources? I would much rather point `lazygal` at a couple of existing directories with photos than first having to copy those all to a temporary directory just for running `lazygal` once.

**Comment by niol** [comment]
`lazygal` follows symlinks which seems to address your usecase and many more: it makes it possible to put any directory whenever you want in the produced album. Does that work for you?

**Comment by ritzmann** [comment]
Sure that works, could actually make that explicit in the documentation? I think it still is not the most convenient way to do it because you need to manually create and afterwards delete these symlinks.

**Comment by niol** [comment]
My opinion on this is that this will make the code even more complex for something less usefull than symlinks support. I actually leave the source directory with symlinks in my homedir as it does not take disk space and allows me to update the album. If you can come up with a simple patch that handle this, I'll integrate it. Meanwhile, I'll improve the documentation.

**Comment by ritzmann** [comment]
Thank you for the quick response!
