### ISSUE TITLE
GExiv2 link in readme is broken

### ISSUE THREAD

**Issue by Nekkowe** [niol/lazygal#19]
I'd love to get this running for my website, but I'm running into a few stumbling blocks -

The most immediate one is that the link to the GExiv2 in the readme file (http://redmine.yorba.org/projects/gexiv2/wiki) is broken. Near as I can tell, there is not currently a Yorba.org at all.

Is [this](https://gitlab.gnome.org/GNOME/gexiv2/-/tree/master) the same GExiv2? The build process looks like a bit of a pain, what kind of advantage does it have over [exiv2 on pip](https://pypi.org/project/exiv2/) (formerly "python-exiv2")?

**Comment by niol** [comment]
Thanks for your interest.
The switch from pyexiv2 to GExiv2 was done years ago because pyexiv2 was unmaintained. I had not noticed that the projet had been revived. Gexiv2 is well maintained, that's why the switch happened.

**Comment by Nekkowe** [comment]
I see, thank you!

If I could pick your brain on something - I was hoping to recommend lazygal to some friends and acquaintances who are looking for a simple gallery solution that lets them place their digital artworks on their static websites. 

Few of them are on Debian/Ubuntu/Mint etc. - a couple use Windows, still, even - and since Gexiv2 isn't installable via pip, I'm worried that the build process with `meson` and `ninja` and all that will be a bridge too far for most (or all) of them.

Is there any simple way to make the setup for all this easier? I'm half tempted to try and set some time aside to rewrite the relevant parts to pipy's exiv2 or the new pyexiv2 and submit a pull request, not that I understand exiv data (or Gexiv2 for that matter) that well yet... maybe one day, the setup can be as simple as `pip install lazygal` regardless of platform.

In any case, lazygal is wonderful, thank you for your work! I especially appreciate the nice subdirectory thumbnails, the arrow key navigation, and the RSS feed.

**Comment by niol** [comment]
Thanks a lot for your feedback.
pyexiv2 support was removed in 73a590633910220e20377dd199715bce4ef8a03e so maybe reverting that patch and a few adjustements would do the trick. The metadata stuff has an extensive test suite so this will be easy to validate.
I have never looked into pip so cannot help on this.
I would accept pull request on those two items.
