### ISSUE TITLE
Minor typo "dl_asset"

### ISSUE THREAD

**Issue by Troon** [niol/lazygal#5]
I have upgraded to 0.9.4 (for the `no-video` option: nice work!) and got the following error message on running:

```
Theme inverted: manifest.json reference error: files not found:
	/usr/local/share/lazygal/themes/inverted/jquery.js

The following actions may fix this:
	- Running ./setup.py dl_asset
	- Installing deps from your distribution
```

It took me a while to work out that the correct command is `dl_assets` with the "s" on the end.

This typo is in `themes.py` line 136 at time of writing.

**Comment by niol** [comment]
Thanks for reporting!
